apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  clusterIP: None
  ports:
  - name: web
    port: 9093
  - name: tcp-mesh
    port: 9094
  - name: udp-mesh
    port: 9094
    protocol: UDP
  selector:
    app: alertmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - args:
        - --config.file=/etc/alertmanager/config/alertmanager.yaml
        - --cluster.listen-address=[$(POD_IP)]:9094
        - --storage.path=/alertmanager
        - --data.retention=120h
        - --web.listen-address=:9093
        - --web.external-url=http://127.0.0.1:9093
        - --web.route-prefix=/
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: quay.io/prometheus/alertmanager:v0.21.0
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /-/healthy
            port: web
        name: alertmanager
        ports:
        - containerPort: 9093
          name: web
        - containerPort: 9094
          name: mesh-tcp
        - containerPort: 9094
          name: mesh-udp
          protocol: UDP
        readinessProbe:
          httpGet:
            path: /-/ready
            port: web
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    receivers:
      - name: "null"
    route:
      group_by:
        - job
      group_interval: 5m
      group_wait: 30s
      receiver: "null"
      repeat_interval: 12h
      routes:
        - match:
            alertname: Watchdog
          receiver: "null"
