kind: Service
apiVersion: v1
metadata:
  name: bridge
spec:
  selector:
    app: bridge
  ports:
  - name: promui
    protocol: TCP
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge
spec:
  selector:
    matchLabels:
      app: bridge
  template:
    metadata:
      labels:
        app: bridge
    spec:
      containers:
      - name: bridge
        image: patam-image
        ports:
        - containerPort: 8080
